### ISSUE TITLE
Filter tags when selecting

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#1008]
When there are a lot of tags, adding a new tag to a person (or a smart search filter) means having to scroll through a very long list. A simple filter input in the `SelectPersonTagsPane` would make this much more efficient.

**Comment by MikaelJohnAndersson** [comment]
PR #1017 opened for this issue. Though I'm wondering if it would it be preferable to create a new component for this? I can filter tags using a `TextInput` component preserving the filter query in`SelectPersonTagsPane` state, but I would like to create something along the lines of a `TagsFilter` component preserving filter query state and containing filter logic while showing an indication  of no. of matches to the user.
