### ISSUE TITLE
Warn when trying to import invalid file

### ISSUE THREAD

**Issue by niklasva82** [zetkin/organize.zetk.in#1049]
When trying to import a non-xlsx file, nothing happens. It would make sens to display a warning saying unsupported file format and which file formats are allowed.

**Comment by richardolsson** [comment]
Good point!

The library that we are using to parse the files supports XLSX and ODS. Any other file format, including CSV, will not work at this point and should be detected.

**Comment by niklasva82** [comment]
> Good point!
> 
> The library that we are using to parse the files supports XLSX and ODS. Any other file format, including CSV, will not work at this point and should be detected.

It seems ODS is not valid, only XLSX. The libary function seems to throw an error on import of an ODS file.

**Comment by richardolsson** [comment]
ODS has worked before, but it's not really a problem if it's been deprecated. CSV is more important, as that's more common. I have created issue #1054 to track CSV importer progress.
