### ISSUE TITLE
View pagination

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#1116]
Implement (client-side) pagination of views. The client store can easily handle thousands of rows, but the React UI cannot. Preliminary tests show acceptable UX with 500 rows visible at a time.

**Comment by sam-mcmurray** [comment]
I can do this if no one else is already working on it

**Comment by richardolsson** [comment]
Great @sam-mcmurray!

I would recommend an approach like this:

- [ ] Create a `<PageSelect>` component with a `pageCount` property and an `onChange` callback
- [ ] Add a `<PageSelect>` to `PersonViewTable` if there are more than 500 rows
- [ ] Set the state of `PersonViewTable` based on the page select when it changes
- [ ] `slice()` the array of rows according to page before rendering

To keep it simple, the `PageSelect` could be a crude `<ul>` list initially, and then we can make it look nice later. Something like this:

```jsx
// new file src/misc/PageSelect.jsx, written freestyle so may contain mistakes
export default function PageSelect(props) {
  const items = [];

  // Create array of <li> list items
  for (let i = 0; i < props.pageCount; i++) {
    items.push(
      <li key={i}
        onClick={ () => props.onChange? props.onChange(i) : null }
        >{ i + 1 }
      </li>
    );
  }

  // Return <ul> list containing the items
  return (
    <ul>{ items }</ul>
  );
}
```

**Comment by richardolsson** [comment]
I realized I had created a bug in the way I was generating items in my example code above. I've edited it now to use `map()` on an array of numbers created using `Array(n).keys()` ([see StackOverflow](https://stackoverflow.com/a/37980601/229824) on where this approach comes from).
