### ISSUE TITLE
Revisit pane header

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#115]
The pane concept has branched out into several different types of layout, specifically looking at the header which ideally should be consistent. Revisit the concept, asking these questions (and possibly more):

* How can pane headers be more consistent?
* Is it right to sometimes have elements above the title, like the mini-calendar?
* Should the view switch, campaign filter, add buttons et c go in the header?
* Should the header scroll with the pane content, or be static at the top?

## Examples
These are some examples of what headers look like in different contexts now

### A simple header
A simple header with just an add button.

![image](https://cloud.githubusercontent.com/assets/550212/9608216/945f447c-50cd-11e5-980c-4d52533a4fcd.png)

### More complex header
A header with a view switch, a filter and an add button (not shown).

![image](https://cloud.githubusercontent.com/assets/550212/9608225/a2e6ee00-50cd-11e5-9dc6-4b67fa5dcc5d.png)

### Content above header
The header is pushed down by another piece of UI, the mini-calendar, which makes the header location inconsistent with other sub-sections (even within the same section).

![image](https://cloud.githubusercontent.com/assets/550212/9608236/b0ed1506-50cd-11e5-915c-bf2d3b201170.png)

### Inconsistent heights
The header in the section pane (left) is not the same height as the header in the overlay pane (right), with "Rosa Luxemburg" rendered lower than "People".

![image](https://cloud.githubusercontent.com/assets/550212/9608258/d67710f6-50cd-11e5-8833-0465e4c559a3.png)

**Comment by richardolsson** [comment]
Of course we must not forget the very special case that is the maps section, where there is no text header at all, but still both a view mode switch and an add button. This pattern may reappear in other types of sections in the future.

![image](https://cloud.githubusercontent.com/assets/550212/9637502/73797546-51a1-11e5-9fc8-503eb80be087.png)

**Comment by jensborje** [comment]
<img width="1282" alt="skarmavbild 2015-09-06 kl 18 10 15" src="https://cloud.githubusercontent.com/assets/1271517/9705370/9ebf9af4-54c2-11e5-82f1-f8bbe4347f9d.png">
<img width="1106" alt="skarmavbild 2015-09-06 kl 18 11 11" src="https://cloud.githubusercontent.com/assets/1271517/9705371/b3e2a2a0-54c2-11e5-94b0-8745119e9f1a.png">
