### ISSUE TITLE
Order alphabetically

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#1161]
A bunch of lists and select boxes are sorted by the default order from the API, which is not very user friendly.

Lets work together to find them. Here are some that I can think of:

- [x] Smart Search select in `PersonViewsPane`
- [x] Tag select in `AddViewColumnPane`
- [x] Smart Search select in `AddViewColumnPane`
- [x] Tag list in Manage section
- [x] Smart Search list in Manage section
- [x] View items in Views section

**Comment by richardolsson** [comment]
Two items fixed by #1207.

**Comment by olleolleolle** [comment]
#1230 should cover the rest of this list.

**Comment by richardolsson** [comment]
Fixed by #1230
