### ISSUE TITLE
Deal with deleted option in survey pane

### ISSUE THREAD

**Issue by niklasva82** [zetkin/organize.zetk.in#1165]
It is possible to delete an option in a survey question after it was created and after an answer was submitted. But if you do, all other answers in any survey submission which selected  that option will become unreadable because the pane will not render.

To reproduce:
1. Create a survey with a multiple choice question.
2. Submit a survey response selecting all the options.
3. Delete one of the options from the question.
4. Attempt to open the survey response.

Expected: Display the survey submission including the non-deleted options, or even show the deleted option as well.

Actual: Submission is not shown because qo is not defined on line 222 of SurveySubmissionPane, and rendering of the pane crashes.

**Comment by niklasva82** [comment]
Encountedred this problem again. This should be a simple fix to simply skip that answer. Next hackathon?

**Comment by richardolsson** [comment]
This sounds to me like a bug in the API. If the option has been deleted, there should be nothing coming back from the API that relates to that option.
