### ISSUE TITLE
Bug rendering custom field in query

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#1250]
Steps to reproduce:

1. Create a Smart Search query or all assignment
2. Open/edit the query
3. Add a filter for "Custom Field"
4. Select a custom field (I experienced this with a date field, but should be same for any type)
5. Configure the filter
6. Save and close the Smart Search
7. Refresh the page (to clear state)
8. Open the edit pane for the query again

Expected results: Should look exactly like after step 5
Actual results: The "Choose field" select box is the only one showing, probably because the list of fields had not loaded when the filter list was rendered

**Comment by richardolsson** [comment]
Did you try with a date field? At least with a date field, this is what it looks like to me after step 8, even though the configuration is clearly there (because the query works):

![image](https://user-images.githubusercontent.com/550212/110584475-8d7c0400-816f-11eb-9b14-5a1651fdbe1e.png)

As theorized in the description above, this is probably because the list of fields had not loaded when I opened the query the second time (after refreshing the page in step 7 to clear state). If I close the pane and open it again, the state will have loaded, and the widget looks right.

**Comment by niklasva82** [comment]
I can reproduce this when refreshing with the edit pane open now. Should be a simple fix.
