### ISSUE TITLE
External ID as 36 char uuid in import

### ISSUE THREAD

**Issue by joe-irving** [zetkin/organize.zetk.in#1326]
I have been trying to work out how to sync from Action Network to Zetkin using the people upload feature. Action Network lets you download CSV files of people on the system, but the ID is a string with letters numbers and hyphens (i.e. a UUID).

Not sure exactly what is needed for this, or how big of a change, but it would be great to have this as a simpler system for syncing

**Comment by richardolsson** [comment]
This sounds like the type of field that you would use as what Zetkin calls an "External ID". The purpose of the "External ID" is to be able to merge people that are continuously imported from another system.

Note that this is not an automatic sync, it's a manual upload feature, but it is available through the API so it is possible to automate it externally.

**Comment by joe-irving** [comment]
Thanks for the speedy response to this!

Ah sorry it looks like I got this slightly wrong, I thought there was an issue with External ID not accepting strings but it actually looks like it isn't accepting the IDs because they are over 12 characters. It looks like [36 characters is standard](https://en.wikipedia.org/wiki/Universally_unique_identifier) across a lot of systems, do you think this is something that can be changed?

For now not having an automatic sync should be okay, it can just be a process that we/others learn so more time can be spent on getting any automatic sync things right.

For reference, here is the an example upload attempt of a downloaded CSV from Action Network:

![Pre import attempt](https://actionnetwork.org/user_files/user_files/000/091/749/original/Screenshot_from_2023-05-03_06-20-24.png)

![Error from attempted import](https://actionnetwork.org/user_files/user_files/000/091/750/original/Screenshot_from_2023-05-03_06-20-42.png)
