### ISSUE TITLE
URL error when opening Actions

### ISSUE THREAD

**Issue by EivindEE** [zetkin/organize.zetk.in#1329]
When going to the [Actions] page, the page does not load properly.
I'm unsure if it is connected, but the console shows an attempt to load invalid URLs, with a `blob://null` before the URL propper.

<img width="685" alt="image" src="https://github.com/zetkin/organize.zetk.in/assets/780999/adec5824-3d40-4f78-b61b-4e726c7b3959">

Browser: Safari, Versjon 16.4 (18615.1.26.110.1)
Organization: Oslo SV -> Sagene SV
Time: ~20:00 31.07.2023

**Comment by richardolsson** [comment]
Thanks a lot for submitting this bug report! 🙌 

We will see if we can look into it, but I wonder if you can provide any additional information, e.g. steps to reproduce or a URL where you are experiencing the issue?

**Comment by niklasva82** [comment]
Can't reproduce this.
