### ISSUE TITLE
Action status in ActionList

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#181]
Somehow the action list must indicate the status of an action, i.e.:
- Enough participants?
- Reminders sent?
- Cancelled?

**Comment by richardolsson** [comment]
This is what it looks like today.

![image](https://cloud.githubusercontent.com/assets/550212/9704895/f6d4cc40-54b4-11e5-8a06-02fd2768af92.png)

**Comment by JohanStrandell** [comment]
![zetkin action list](https://cloud.githubusercontent.com/assets/552072/9705342/daddd722-54c1-11e5-9d2e-75970366822e.png)

**Comment by JohanStrandell** [comment]
![zetkin action list without gaps](https://cloud.githubusercontent.com/assets/552072/9705490/887da34a-54c6-11e5-8b28-8a812790a831.png)
![zetkin action list inline dates](https://cloud.githubusercontent.com/assets/552072/9705491/88a7b388-54c6-11e5-8d2d-281addc68e0a.png)

**Comment by jensborje** [comment]
<img width="971" alt="skarmavbild 2015-09-06 kl 19 07 16" src="https://cloud.githubusercontent.com/assets/1271517/9705616/8679e6a4-54ca-11e5-9f83-34a96dcbcca9.png">


Test of concepts in high def.

**Comment by JohanStrandell** [comment]
Month names only on new month, add weekday instead
![zetkin action list month names](https://cloud.githubusercontent.com/assets/552072/9705660/678e7a82-54cc-11e5-9573-b63e18c62fac.png)

Gaps between each day, no separate indication for longer gaps:
![zetkin action list no gaps](https://cloud.githubusercontent.com/assets/552072/9705662/8226be54-54cc-11e5-8f34-f9c57a0dc942.png)

**Comment by richardolsson** [comment]
Same list legacy Zetkin:

![image](https://cloud.githubusercontent.com/assets/550212/21681316/0e087bd6-d34f-11e6-9ca2-4370c98ad463.png)

**Comment by richardolsson** [comment]
What could or should be indicated, explicitly or implicitly, directly or in response to user action, in descending order of importance:

* Number of participants, vs minimum number of participants required
* Responses not yet booked as participants
* Whether all participants have received e-mail reminders
* Whether the action is visible/published or hidden/unpublished
* Whether action has been cancelled
* Whether action is in the past or future
* Whether there are any organizer notes (and if there are, the note text)
* Whether there is any public information text (and if there is, the info text)
* Whether the action is prioritized
* Participant gender balance

**Comment by richardolsson** [comment]
Also note that the campaign to which an action belongs should be displayed in the list, as described in #224.

**Comment by jensborje** [comment]
Proposal for January launch:
![skarmavbild 2017-01-06 kl 11 50 09](https://cloud.githubusercontent.com/assets/1271517/21715703/5edefb90-d406-11e6-992b-1eb710a3f16e.png)

Alternative positioning for priority and visibility status icons:
![skarmavbild 2017-01-06 kl 11 50 17](https://cloud.githubusercontent.com/assets/1271517/21715792/d66cf284-d406-11e6-939b-f3ab5c34e78d.png)

**Comment by richardolsson** [comment]
As of recent changes (#359) the status of this list of indicators is now:

* ~Number of participants, vs minimum number of participants required~
* ~Responses not yet booked as participants~
* ~Whether all participants have received e-mail reminders~
* Whether the action is visible/published or hidden/unpublished
* Whether action has been cancelled
* ~Whether action is in the past or future~
* Whether there are any organizer notes (and if there are, the note text)
* Whether there is any public information text (and if there is, the info text)
* Whether the action is prioritized
* Participant gender balance

**Comment by richardolsson** [comment]
None of the remaining pieces of information actually exist as individual features. No need to keep this issue around.
