### ISSUE TITLE
SelectPeoplePane styling

### ISSUE THREAD

**Issue by jensborje** [zetkin/organize.zetk.in#254]
SelectPeoplePane needs some styling besides the PeopleList component.
- Styling of Selected list when empty
- Remove icon on hover list item in Selected list
- Add pane footer / move buttons to this

**Comment by richardolsson** [comment]
Given the short amount of time left, this is not a priority.

**Comment by richardolsson** [comment]
Maybe use list bulk selection framework instead? The selection that has already been created as part of opening the pane could theoretically just be passed into the `PersonList` and have the checkboxes update correctly.

**Comment by richardolsson** [comment]
We're moving away from this pane, instead using the `SelectPersonWidget`. Closing as no longer relevant.
