### ISSUE TITLE
LocationListItem doesn't pass id to LocationPane

### ISSUE THREAD

**Issue by jensborje** [zetkin/organize.zetk.in#275]
When clicking on a LocationListItem in http://organize.zetkin/maps/, it passes whole object rather than the location data.

![skarmavbild 2016-06-07 kl 16 25 53](https://cloud.githubusercontent.com/assets/1271517/15861386/89ecd7e4-2ccc-11e6-9872-7409e8e17da1.png)
![skarmavbild 2016-06-07 kl 16 26 22](https://cloud.githubusercontent.com/assets/1271517/15861417/9e38ca96-2ccc-11e6-8f11-abbcc6b08b4f.png)

**Comment by richardolsson** [comment]
This seems to no longer be the case, although I'm unsure what kind of behaviour the bug was causing, so it's difficult to reproduce. Closing, assuming it's no longer relevant after the September list refactor.
