### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by jensborje** [zetkin/organize.zetk.in#283]
I would like to update the header styling to make it coherent with rest of the site.

I suggest the following: 

![skarmavbild 2016-06-16 kl 19 37 07](https://cloud.githubusercontent.com/assets/1271517/16127086/3c4cb4f6-33fb-11e6-92f9-e9fc1e5da80d.png)

**Comment by jensborje** [comment]
Any thoughts on this @richardolsson ?

**Comment by richardolsson** [comment]
LGTM. We need a proper logo sooner or later though. And I wouldn't mind if the search field was really big. :)

**Comment by richardolsson** [comment]
This has been fixed via the aforementioned PR.
