### ISSUE TITLE
Style call assignment list

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#334]
The call assignment list (at /dialog/assignments) is currently very crudely designed.

![image](https://cloud.githubusercontent.com/assets/550212/21673660/51d7758a-d32a-11e6-9083-801b75bdb259.png)

**Comment by richardolsson** [comment]
Maybe something inspired by the GitHub milestone listing?

![image](https://cloud.githubusercontent.com/assets/550212/21673692/6b9e3b2a-d32a-11e6-94a1-6dcd22195a5b.png)

**Comment by jensborje** [comment]
Something like this?

![skarmavbild 2017-01-11 kl 15 09 47](https://cloud.githubusercontent.com/assets/1271517/21851604/17b5b2f0-d810-11e6-99f5-15562d4ba73a.png)

**Comment by richardolsson** [comment]
That's nice! Some thoughts:

* Maybe make success rate a percentage instead of number of successful calls?
* The progress bar in `CallAssignmentPane` is red, so maybe this should be to?
* The current implementation of `CallAssignmentItem` already has a list of callers, similar to the one in `ActionListItem` (in fact, using the same `ParticipantList`). Maybe keep that somehow instead of just printing number of callers?
* Maybe add a "Stats" label in the header over the pseudu-column that contains the stats?

**Comment by richardolsson** [comment]
RE the caller/participant list: It would also be completely fine to remove the list of callers if we want to. In fact, that would reduce risk of bugs. I'm just thinking since it's already implemented, maybe we could keep it, but I'll let you decide.

**Comment by jensborje** [comment]
I agree with the input.

I removed the caller/participant list since you assign callers in the opened pane. Having them in the list might cause confusion on where you do this, as we allow it in the ActionList. It also makes somewhat sense that the list is a summary and you interact with it do view details.

**Comment by richardolsson** [comment]
Ok great!

![Make it so](https://media.giphy.com/media/wNlks0ID1igO4/giphy.gif)

**Comment by jensborje** [comment]
I'm on it. Updated mockup:

![skarmavbild 2017-01-11 kl 15 30 11](https://cloud.githubusercontent.com/assets/1271517/21852319/e4b91b96-d812-11e6-9911-0856bad28069.png)

**Comment by richardolsson** [comment]
How do we deal with really long titles? It could easily be something like "Mobilize experienced activists to First of may campaign 2017", or (real-life example) "Socialisterna ringer: medlemsenkät + förfrågan medlemsskap (3)". Do we truncate it, make the list wider, or should we amend the design to allow for longer names?

**Comment by jensborje** [comment]
My intention is to allow the title to be in two rows height. We have the room for it.

**Comment by richardolsson** [comment]
Resolved by #378.
