### ISSUE TITLE
Status indicators in action list

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#339]
There are several states to an action that need to be indicated in the action list (find current design attached).

![image](https://cloud.githubusercontent.com/assets/550212/21674547/6f614c6c-d32e-11e6-8a2f-011df610b5b4.png)

At least, the list needs to indiciate:

* Whether there are more sign-ups (responses) that can be booked
* Whether all reminders have been sent

Ideally, it should also be visible in the list:

* Whether there are organizer notes, and if there are, the note text

**Comment by jensborje** [comment]
See #181 for proposals
