### ISSUE TITLE
More information in CallPane

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#342]
Currently only a minimal amount of information about a call is displayed in `CallPane`. The pane should at least contain the same information that is presented by the call log (`TargetPane`) in Zetkin Call.

Once #326 is implemented, there should also be organizer notes here. Once message from caller to organizer has been added to the API, that should also be here (and the possibility to mark call with organizer action taken).

**Comment by richardolsson** [comment]
Make sure the following pieces of information and features are present in the pane:

* Target and caller names, including links to `PersonPane` for either or both?
* Date of call
* Call status, using a similar indicator to the three-step bar in Zetkin Call
* Caller notes
* Whether organizer action is needed (`organizer_action_needed`)
* Message from caller to organizer (`message_to_organizer`)
* Whether organizer action was taken (`organizer_action_taken`)
* A way to flag call as `organizer_action_taken = true`

**Comment by jensborje** [comment]
Design mockup

![skarmavbild 2017-01-19 kl 17 46 58](https://cloud.githubusercontent.com/assets/1271517/22115994/5e4d7116-de6f-11e6-8885-a1b20f58871e.png)

![skarmavbild 2017-01-19 kl 17 47 15](https://cloud.githubusercontent.com/assets/1271517/22115999/63e6e238-de6f-11e6-934a-9c13d4835588.png)
