### ISSUE TITLE
Overhaul of approach to add/edit locations

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#346]
There are several issues with the way locations are added and edited, especially in the "maps" section of Organize:

* The `AddLocationPane` requires the large, full-section map to be visible for it to work.
* The above means that creating locations from other sections require the separate `AddLocationWithMapPane`, suffering from inconsistencies, weird multi-pane interactions et c.
* Because of the way this has been solved, only one location can be added/edited at a time.
* Eventually, we will add layers and shapes that need to be edited somewhere the same way that locations are, and it won't fit in the same map.

Based on recent discussions, here's a suggested new approach:

* Make full-section map read-only (used to display and open locations, eventually shapes and layers).
* Move add/edit locations to a separate sub-section where they are displayed as an order list/grid.
* Make room for similar, future sub-sections for shapes and layers.
* To edit/create a location, open up the form pane, and from there a separate map pane to move it around.

**Comment by richardolsson** [comment]
Fixing this should mean that the `*WithMap`are removed which should make #217 irrelevant.

**Comment by jensborje** [comment]
Mockup / interactive demo:
https://xd.adobe.com/view/f1985b37-aee3-4347-88c6-dc0426c5a598/
