### ISSUE TITLE
Improve CallList

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#386]
`CallList` should be restyled to be more consistent with other dated lists in Organize. We also need to make sure that it includes the following pieces of information:

* Target person
* Caller
* Status (reached/not reached)
* Date
* Whether organizer action is needed
* Whether organizer action was taken

If we can somehow include the following without cluttering the list, that would be nice, but it's not a requirement:

* Message (truncated) to organizer
* Message (truncated) to future callers

When performing this revamp, lets try to accommodate the fact that at some point in the future, this list will not just contain calls but also other types of contact, e.g. e-mail and SMS. We should not put too much effort into this right now though.

**Comment by richardolsson** [comment]
This could ideally be submitted as a single pull request along with a resolution to #342.

**Comment by jensborje** [comment]
A status can be either _allocated_, _reached_ or _not reached_.

**Comment by jensborje** [comment]
Design mockup

![skarmavbild 2017-01-19 kl 11 46 12](https://cloud.githubusercontent.com/assets/1271517/22103820/e9391c4a-de3c-11e6-9a7b-03723b1357d7.png)
