### ISSUE TITLE
Survey builder

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#413]
Create a survey builder as a pane or set of panes, to be located somewhere in the new Surveys section (#412). In it's simplest form, the builder needs to support:

* Creating surveys and editing survey settings (title, description, access et c)
* Adding and editing text blocks (title and wysiwyg content)
* Adding and editing questions
  * Question and help text/description, as well as settings (e.g. is it required?)
  * Various response types and settings
    * Text (single-line or multi-line)
    * Options (single or multiple, with or without free text option)
* Removing items
* Re-ordering items (questions and text blocks)

Nice-to-have features include:
* Dragging to re-order items
* Separate order for callers
* Separate text blocks for callers

**Comment by richardolsson** [comment]
Notes from UX workshop 2017-02-08:

## Pane layout
* Root pane with surveys
* AddSurveyPane with form creates a survey, opens it up in SurveyPane
* SurveyPane is similar to CallAssignmentPane
  * Access list is separate section of pane (analogous to callers)
  * Content items are edited in separate pane (analogous to instructions in a call assignment), lets call it SurveyOutlinePane for now.

## SurveyOutlinePane
Content items (questions and text blocks) of a survey are edited in this pane.
* SurveyOutlinePane contains summary of each item (like headline, type and number of options for questions), but not all the text content.
* Move items up and down to re-order (ideally drag and drop)
* Click to edit a question/text block (in a separate pane or expanded state?)
* Add items by selecting an item type (question or option). A new pane opens which allows you to edit the question (EditQuestionPane) or text block (EditTextBlock).
* New items are always appended to the end of the outline.
* Outline should be saved to server whenever a new item is added or the order is changed. Saving by explicitly clicking somewhere is not necessary.

## Options
* Options can be edited even after responses have been collected. Changing the spelling or wording of an option should be allowed, and _retain the collected responses_. This is how Zetkin works today, and needs to be properly communicated by the interface.
* Possible solutions are to make it difficult to edit options, or to warn when editing options on a survey for which there are responses collected.
* Options are edited inside the question (pane).
* Options can be edited, deleted (responses are removed too) or hidden (responses are retained in summaries and statistics).

## Preview
* Previewing could be in a new window (live on www), in a new pane, or another view state in the same pane.
* Preview should be accessible from the outline.
* Preview requires saving (for API reasons) so it must be made clear that opening the preview means updating the survey (which may or may not have been published already).

**Comment by richardolsson** [comment]
Completed to the extend necessary for PR 17-1. Work will continue in forthcoming sprints.

**Comment by jensborje** [comment]
Should we be able to toggle if a survey is published or not? By published I mean if it should be visible for those having access to it or not.

**Comment by richardolsson** [comment]
@jensborje: Yes, that would be a nice feature eventually, but right now we do not have such a feature in the Platform API.

**Comment by richardolsson** [comment]
Status as of today:

* ~~Creating surveys and editing survey settings (title, description, access et c)~~ 
* ~~Adding and editing text blocks (title and wysiwyg content)~~ (not wysiwyg)
* ~~Adding and editing questions~~
  * ~~Question and help text/description, as well as settings (e.g. is it required?)~~
  * ~~Various response types and settings~~
    * ~~Text (single-line or multi-line)~~
    * ~~Options (single or multiple~~, with or without free text option)
* Removing items
* Re-ordering items (questions and text blocks)
* Dragging to re-order items
* Separate order for callers
* Separate text blocks for callers

**Comment by richardolsson** [comment]
Now working on removing and dragging to re-order.

**Comment by jensborje** [comment]
I suggest removing items should be done while editing.

Preferably, we will implement it as what comes out from #302, but until that issue is solved, I suggest a button like bellow.

![screen shot 2017-04-28 at 11 03 30](https://cloud.githubusercontent.com/assets/1271517/25522211/610d04e4-2c02-11e7-824c-349f539333d5.png)

**Comment by richardolsson** [comment]
Have you considered how this would work when there are 20 response options? Should the delete button be under the list of options?

**Comment by jensborje** [comment]
The delete button is bellow the SurveyQuestionForm and above the SurveyQuestionOutline.

Removing options could be done by adding a trashcan icon when editing the option, next to the cancel button.

**Comment by richardolsson** [comment]
Status post #581:

* ~~Creating surveys and editing survey settings (title, description, access et c)~~ 
* ~~Adding and editing text blocks (title and wysiwyg content)~~ (not wysiwyg)
* ~~Adding and editing questions~~
  * ~~Question and help text/description, as well as settings (e.g. is it required?)~~
  * ~~Various response types and settings~~
    * ~~Text (single-line or multi-line)~~
    * ~~Options (single or multiple~~, with or without free text option)
* ~~Removing items~~
* ~~Re-ordering items (questions and text blocks)~~
* ~~Dragging to re-order items~~
* Separate order for callers (tracked separately in #583)
* Separate text blocks for callers (tracked separately in #583)

Having created a separate issue for caller-related features this can now be closed.
