### ISSUE TITLE
Organize dashboard icon for Surveys

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#414]
We plan to release the survey feature in the beginning of March. Until then we need to create a dashboard icon for surveys, similar to the ones for People, Campaign, Dialog and Maps.

![image](https://cloud.githubusercontent.com/assets/550212/22374981/9c73299c-e4a8-11e6-80be-4b4b5162fcd8.png)

Maybe some combination of a survey form and a chart/diagram?

I'm assigning this to you @Bagera since you've created the other icons. Let me know if you don't have time to do this in February.

**Comment by richardolsson** [comment]
See also #417 for new visual context.

**Comment by jensborje** [comment]
A simple solution could be like this.
![dashboard-icons](https://cloud.githubusercontent.com/assets/1271517/23135772/2ec16cc4-f79a-11e6-96a3-00530a0a1339.png)

Do note that details like shadows and other refinements are to be added.

**Comment by richardolsson** [comment]
Looking goooood!

Do you think it's too messy with some sort of element indicating what surveys can be used for (and not just what they _are_)? Like the piechart in my mock-up, or anything else that similarly indicate a summary.
