### ISSUE TITLE
Style SurveySubmissionPane

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#459]

**Comment by jensborje** [comment]
To be included in list:
- Title
- Open or not
- Callers only
- Number of submissions?

**Comment by richardolsson** [comment]
Is that last comment really on the right issue? This issue concerns styling of `SurveySubmissionPane`, i.e. the pane pictured in the attached screenshot. Your comment seems to be about `SurveyList`, for which I've created a separate issue #486.

![image](https://cloud.githubusercontent.com/assets/550212/23375907/5aa998ee-fd2a-11e6-89ba-f3639562bf0d.png)

**Comment by jensborje** [comment]
You're right. Was in a hurry when sending it off :)

**Comment by jensborje** [comment]
Here's some UI design - yay or nay?

![screen shot 2017-02-28 at 15 52 07](https://cloud.githubusercontent.com/assets/1271517/23410049/1d322612-fdce-11e6-8a27-1b6c1bcc84a2.png)

![screen shot 2017-02-28 at 15 52 24](https://cloud.githubusercontent.com/assets/1271517/23410054/255c0268-fdce-11e6-90f3-ec8772ac84cf.png)

![screen shot 2017-02-28 at 15 52 37](https://cloud.githubusercontent.com/assets/1271517/23410056/27fd6412-fdce-11e6-9251-a56a0dcab440.png)

**Comment by richardolsson** [comment]
Yay! Looking amazeballs. 

![Make it so](https://media3.giphy.com/media/wNlks0ID1igO4/200_s.gif)
