### ISSUE TITLE
Style SurveySubmissionList

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#460]
To be included in list items:

* Name of the survey
* Date of submission
* Respondent
  * Can be anonymous (`respondent` is `null`)
  * Can be connected (has `id` field) – show name and avatar
  * Can be signed with name and e-mail but not connected (has no `id` field) – show name only
* Indication on whether connected to person. Anonymous respondents would likely not be possible to connect, but unconnected, signed submissions can. Flag somehow?

Nice to have:
* Percentage of survey to which there are responses in submission (ratio between number of `responses` in submission and questions in survey)

**Comment by jensborje** [comment]
Current work in progress

<img width="660" alt="screen shot 2017-02-25 at 16 26 28" src="https://cloud.githubusercontent.com/assets/1271517/23332272/32590b86-fb77-11e6-97e9-a4c55e30779d.png">

**Comment by richardolsson** [comment]
Looks amazing!

At first I didn't understand the connection icon. Maybe we should use the same scheme that we are using in the `ActionListItem`, where a single icon (e.g. the lightning bolt _or_ the person icon) is combined with either a checkmark (connected), dots (can be connected) or a cross (can't be connect, i.e. was filed anonymously).

There are many options, and I'm still trying to sort them out in my head. Unless you will be working more on this over the weekend, lets discuss it on Monday.

Again, this is looking great!

**Comment by richardolsson** [comment]
Oh, I missed something, and it's not in the list in the original issue (I'll edit and add it). The name of the survey is missing. That's a very important piece of information that needs to be clearly visible as you're scrolling through the list.

**Comment by jensborje** [comment]
Some more work done.

- Adding name of survey to each element.
- Refined connection status icons.
  - Changed icon from bolt to chain.
  - Tested to change background of action area based on status.

I think a chain link is a better symbol for if the submission is linked to a person object.

Wether we use background colouring, same colours or coloured icons comes down to priority of attention. If we want to alert the user - then we use background colours. If we want to inform, we use a neutral background and focus on the icons. If they are passive informers like good to know, but not required to notice, then we keep them in same colour and dark grey. If the user should react and notice them we should use colouring.

Same goes for what to colour. In the first example, the linked submission is green but the one after and is left to-be-linked has no colour. This would raise attention to the linked one as it pops out from the crowd.
I lean towards making the to-be-linked as an alert and then have the linked submissions as passive informers, but I leave it open to discussion.

![screen shot 2017-02-27 at 17 05 17](https://cloud.githubusercontent.com/assets/1271517/23368698/ef0f5170-fd0e-11e6-9524-671e4342c31a.png)

![screen shot 2017-02-27 at 17 03 50](https://cloud.githubusercontent.com/assets/1271517/23368680/e1cd6ede-fd0e-11e6-989a-ec40786b897f.png)
