### ISSUE TITLE
Style SurveyList

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#486]

**Comment by jensborje** [comment]
(On the correct issue this time)

To be included in list:
- Title
- Open or not
- Callers only
- Number of submissions?

**Comment by richardolsson** [comment]
I think that's a good breakdown of information to show!

Number of submissions could be something to display down the line, but for now we don't have the APIs to do so in a good way.

"Open or not" could be one of three states (even though we only expose two in the UI right now): Open for anyone, open for authenticated users, open only to specific users.

**Comment by jensborje** [comment]
Design proposal:

![screen shot 2017-03-01 at 16 19 22](https://cloud.githubusercontent.com/assets/1271517/23466266/db43ee5c-fe9a-11e6-993a-fc4cef8b290e.png)

**Comment by richardolsson** [comment]
Looking good! 

Maybe some sort of indication towards whether anonymous submissions are allowed or not?
