### ISSUE TITLE
Revisit importer layout

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#517]
There are several issues with the importer that warrant a revisit to the design of the importer layout, for example:

* Scrolling left/right is hard to understand (see #516)
* Scrolling too far (or too quickly) to the left in Chrome triggers a browser gesture that navigates back.
* Really big datasets affect performance so badly that the interface becomes unusable (see #515)
* The import button overlays content that is about to be imported
* When there are more than one tab/sheet in the Excel file, the user should be encouraged to select the correct one, but when there's only one, there is no need for the sheet select box.

**Comment by jensborje** [comment]
- Choose sheet as a separate step after selecting file
  - Display summary of the sheets content
  - (low prio) Show preview of sheet
- Remove "Import from sheet" selector above columns
- Move "First column" checkbox to top right
- Decrease top margin in pane
- Set `max-height` for rows based on window height and use `overflow:scroll`
  - Paginate rows
  - Add select input in bottom of row area to choose rows
- Always show horisontal scrollbar
- Auto scroll to next column if offscreen after interacting with previous
- Add stepping buttons for columns (see #516)
- Safeguard space in bottom for action buttons (like Import)
- Add abort button in bottom left
- Add confirm step on Import action

**Comment by richardolsson** [comment]
I'll take:
* Choose sheet as separate step (and remove "import from sheet" select)
* Truncate to 100 rows (as opposed to pagination, for now)
* Auto scroll to next column

**Comment by richardolsson** [comment]
Updated list after my recent changes in PR #519:

* ~~Choose sheet as a separate step after selecting file~~
  * Display summary of the sheets content
  * (low prio) Show preview of sheet
* ~~Remove "Import from sheet" selector above columns~~
* Move "First column" checkbox to top right
* Decrease top margin in pane
* Set `max-height` for rows based on window height and use `overflow:scroll`
  * Paginate rows
  * Add select input in bottom of row area to choose rows
* Always show horisontal scrollbar
* ~~Auto scroll to next column if offscreen after interacting with previous~~
* Add stepping buttons for columns
* Safeguard space in bottom for action buttons (like Import)
* Add abort button in bottom left
* Add confirm step on Import action

**Comment by richardolsson** [comment]
Updated after merging #519:

* ~~Choose sheet as a separate step after selecting file~~
* ~~Remove "Import from sheet" selector above columns~~
* ~~Auto scroll to next column if offscreen after interacting with previous~~
* ~~Move "First column" checkbox to top right~~
* ~~Decrease top margin in pane~~
* ~~Set `max-height` for rows based on window height and use `overflow:scroll`~~
* ~~Always show horisontal scrollbar~~
* ~~Safeguard space in bottom for action buttons (like Import)~~
* ~~Add abort button in bottom left~~
* Add stepping buttons for columns (won't fix)
* Add confirm step on Import action (tracked henceforth by #523)
