### ISSUE TITLE
Cannot set column as tags if data is integer

### ISSUE THREAD

**Issue by jensborje** [zetkin/organize.zetk.in#522]
When importing and trying to setup column as Tags, an exception occurs since it expects a string.

![screen shot 2017-03-16 at 14 13 45](https://cloud.githubusercontent.com/assets/1271517/23997795/2dc21f3c-0a53-11e7-92ee-21f28489314a.png)

**Comment by richardolsson** [comment]
Note to self: This is when the column contains integers, not strings.
