### ISSUE TITLE
Section and sub-section icons

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#53]
Draw icons for the many sections and sub-sections to be used in menus. This includes (so far).

__Sections__
These will also need to have tiny versions to be used for selecting search scope.
* People
* Campaign
* Callcenter/Dialog
* Maps

__Sub sections (monochrome)__
* Dashboard ("Back to dashboard")
* People list
* Send/list invites
* Import people
* Actions list/calendar
* Actions distribution
* Campaign playback
* Call assignments
* Call log
* Assignment templates
* Locations list
* Edit officials

**Comment by Bagera** [comment]
What are the sizes? 32px?

**Comment by richardolsson** [comment]
The four top-level section icons currently have placeholders at 180x120 pixels. They can be illustrations more than they are icons. The search scope versions of the four section icons are tiny, 16x16 if possible.

The placeholders for sub-section icons are 70x50 (as seen in [the pane UI prototype](http://prototypes.zetkin.org/organize/panes/)).

**Comment by richardolsson** [comment]
I have updated the list in the original post based on the current state of the app (see changes below). Based on the new visual identity of Zetkin, it is desirable to reuse the circle symbol whenever it makes sense, e.g. to symbolize people.

Removing:
* Join requests
* People tags ("organize")
* Campaign overview
* Campaign list
* Campaign planner

Adding:
* Import people
* Activity list
* Actions distribution
* Campaign playback
* Call assignments
* Call log
* Assignment templates
* Location tags ("organize")
