### ISSUE TITLE
Hard to use without scrollwheel

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#533]
Several parts of Organize are hard to use without scroll wheel.

* Maps, can't zoom
* Campaign calendar, can't scroll (might be all root panes)

**Comment by richardolsson** [comment]
The map zooming was solved by adding zoom in/out buttons to `LocationMap`. However, in some places, like `PlaceLocationPane` the buttons are obscured by the pane footer.

Scrolling issues remain though.

**Comment by jensborje** [comment]
Related to #558
