### ISSUE TITLE
Style forms

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#54]
Forms and inputs need to be styled and laid out consistently. This can be achieved by styling the `Form` and `*Input` components, which currently do not have any class names.

**Comment by richardolsson** [comment]
When doing this, consider that form elements can be against both white and gray backgrounds. On the left is an example of a pane where form elements are on (white) cards, on the right an example where they are directly on the pane.

![image](https://cloud.githubusercontent.com/assets/550212/9652267/19ed9056-521a-11e5-8f3e-2f3bfa758493.png)

**Comment by jensborje** [comment]
<img width="379" alt="skarmavbild 2015-09-06 kl 20 02 11" src="https://cloud.githubusercontent.com/assets/1271517/9705824/3e285c8e-54d2-11e5-80f2-ee3f80aea9ff.png">

Work in progress..

**Comment by jensborje** [comment]
<img width="1011" alt="skarmavbild 2015-09-08 kl 12 45 42" src="https://cloud.githubusercontent.com/assets/1271517/9732906/ad022cd8-5627-11e5-8192-c10b35cf627e.png">

**Comment by richardolsson** [comment]
This was fixed.
