### ISSUE TITLE
Share styles across project

### ISSUE THREAD

**Issue by j0n** [zetkin/organize.zetk.in#70]
The project shares quite a lot of UI-style between apps so there need to be a way to share style-code.

**Comment by richardolsson** [comment]
The zetkin-common repo is now used in Organize as well, but contains only a limited set of components. Not all the mixins etc used across the various apps have been moved to zetkin-common.

**Comment by richardolsson** [comment]
Closing as already tracked in large part by zetkin/zetkin-common#1. No need to keep a separate catch-all ticket open for this. As components that should be shared are found, we can solve them or open new tickets for them specifically.
