### ISSUE TITLE
Possible to create tag with empty string

### ISSUE THREAD

**Issue by skatebird** [zetkin/organize.zetk.in#723]
1. Edit an existing tag
2. Clear the tag name
3. Save

Expected result: empty string not accepted, OR tag is deleted
Actual result: tag with empty string is created

<img width="239" alt="screen shot 2017-12-12 at 15 02 48" src="https://user-images.githubusercontent.com/1061677/33888542-a667e280-df4d-11e7-8237-1f0f7aa5bebb.png">

**Comment by sam-mcmurray** [comment]
i can do this
