### ISSUE TITLE
Survey response pagination

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#762]
Implement pagination on the survey responses sub-section, where currently a huge amount of survey responses are loaded on mount, causing long load times and sluggish interface.

**Comment by richardolsson** [comment]
This is top priority, @Bagera!

**Comment by richardolsson** [comment]
Requires changes to API and must hence be postponsed until next release.

**Comment by jensborje** [comment]
Would be useful with a loading indicator as well!

**Comment by richardolsson** [comment]
@jensborje Please file separate issue for loading indicator.

**Comment by richardolsson** [comment]
This was fixed long ago.
