### ISSUE TITLE
Undefined Undefined in PersonPane

### ISSUE THREAD

**Issue by richardolsson** [zetkin/organize.zetk.in#801]
While a person object is loading, `PersonPane` sometimes displays "undefined undefined" as it's name. This probably happens when there is a person object, but it has the single `name` attribute instead of `first_name` and `last_name`. These types of objects are often sent along with related data (e.g. as the `contact` of an action).

Fix this by using `name` if it exists, and `first_name`/`last_name` otherwise.

**Comment by martinajsongren** [comment]
<img width="490" alt="Screenshot 2019-10-27 at 14 54 37" src="https://user-images.githubusercontent.com/8857989/67635670-bdec3680-f8c9-11e9-9db0-651878154559.png">
Is this already fixed? I don't know how to replicate the bug but this code seems fine to me.

**Comment by richardolsson** [comment]
Looks like it! Thanks for investigating. :)
