### ISSUE TITLE
CampaignForm.scss fails for me

### ISSUE THREAD

**Issue by olleolleolle** [zetkin/organize.zetk.in#963]
## Expxected 

That the command

 `docker-compose -f base.yml -f dev/base.yml -f dev/organize.yml up --build`

Would install a complete website with CSS.

## Actual

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: src/style.scss
Error: Mixin button has no parameter named $transparent
        on line 2421 of src/style.scss
>> }
   --------------------------------------^

    at options.error (/var/app/node_modules/node-sass/lib/index.js:286:26)
```

## What is wrong?

CampaignForm.scss has this

```
    .Button {
        @include button($color:white, $transparent:true);
        line-height: 2em;
    }
```

Running latest `master`.

**Comment by olleolleolle** [comment]
Workaround for master

add to _variables `$small-width: 720px;`
add to mixins: 

```scss
@mixin small-screen {
    @media (max-width: #{$small-width}) {
      @content;
    }
}

```

I removed the `$transparent:...` args from the Button in CampaignForm, and was able to build the thing. Which allowed me to run tests.

**Comment by richardolsson** [comment]
Thanks! Can you check to see if this is the case for the `feature/mobile-interface` branch? We will be merging that shortly, see PR #956.

**Comment by richardolsson** [comment]
This seems to no longer be the case.
